// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://khlguzypjohchdsasaqu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtobGd1enlwam9oY2hkc2FzYXF1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg2NTc4ODgsImV4cCI6MjA3NDIzMzg4OH0.QPvQe0JUDDZ3RwjG3_XFsf0yyGIKq8vsNXU6ljkiDhw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});